name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  yarn-lock:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        id: node
        with:
          node-version: 18.19.0
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
    
      - name: Install
        run: yarn --immutable
      
      - uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 1.0.0-beta.1

      - name: Compile pedersen circuit
        working-directory: ./circuits/pedersen_tree
        run: nargo compile

      - name: Compile mimc circuit
        working-directory: ./circuits/mimc_tree
        run: nargo compile

      - name: Run tests
        run: yarn --immutable
